# Generated by Django 4.1.2 on 2022-10-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_parent_alter_post_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bump_limit',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='default_username',
            field=models.CharField(default='Anonimous', max_length=120),
            preserve_default=False,
        ),
    ]
