# Generated by Django 4.1.2 on 2022-11-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_siteconfiguration_alter_board_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConfiguration',
            new_name='BoardsConfiguration',
        ),
    ]
