# Generated by Django 4.1.2 on 2022-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_file_remove_post_thumbnail_alter_post_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardsConfiguration',
        ),
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to='src'),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumb'),
        ),
    ]
