# Generated by Django 4.1.2 on 2022-12-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_delete_boardsconfiguration_alter_file_src_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='max_file_size',
        ),
    ]
