# Generated by Django 4.1.2 on 2022-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_remove_board_max_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resolution',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
