# Generated by Django 4.1.2 on 2023-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_file_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
