# Generated by Django 4.1.2 on 2022-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_pages_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='max_file_size',
            field=models.IntegerField(default=52428800),
            preserve_default=False,
        ),
    ]
