# Generated by Django 4.1.2 on 2022-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My kawaii imageboard', max_length=256)),
                ('welcome_message', models.TextField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
